//! ADR-0056 acceptance §`Decision`: OpenAPI snapshot for a fixture app
//! with two agents, one workflow, and one tool.
//!
//! The check is intentionally shape-only — the snapshot file is the
//! authoritative document, regenerated by setting
//! `ORK_API_UPDATE_SNAPSHOTS=1` and reviewed in code-review. The test
//! also asserts a few load-bearing invariants explicitly so a typo in
//! the emitter surfaces locally without relying on a diff review.

use async_trait::async_trait;
use ork_a2a::{AgentCapabilities, AgentCard};
use ork_app::OrkApp;
use ork_app::types::{Environment, ServerConfig};
use ork_common::error::OrkError;
use ork_core::a2a::{AgentContext, AgentEvent, AgentId, AgentMessage};
use ork_core::ports::agent::{Agent, AgentEventStream};
use ork_core::ports::tool_def::ToolDef;
use ork_core::ports::workflow_def::WorkflowDef;
use ork_core::ports::workflow_run::{ImmediateWorkflowRunHandle, WorkflowRunDeps};
use serde_json::{Value, json};

struct EchoAgent {
    id: AgentId,
    card: AgentCard,
}

impl EchoAgent {
    fn new(id: &str) -> Self {
        Self {
            id: id.into(),
            card: AgentCard {
                name: id.into(),
                description: format!("{id} agent"),
                version: "0.1.0".into(),
                url: None,
                provider: None,
                capabilities: AgentCapabilities {
                    streaming: false,
                    push_notifications: false,
                    state_transition_history: false,
                },
                default_input_modes: vec![],
                default_output_modes: vec![],
                skills: vec![],
                security_schemes: None,
                security: None,
                extensions: None,
            },
        }
    }
}

#[async_trait]
impl Agent for EchoAgent {
    fn id(&self) -> &AgentId {
        &self.id
    }
    fn card(&self) -> &AgentCard {
        &self.card
    }
    async fn send_stream(
        &self,
        _ctx: AgentContext,
        msg: AgentMessage,
    ) -> Result<AgentEventStream, OrkError> {
        let s = futures::stream::iter(vec![Ok(AgentEvent::Message(msg))]);
        Ok(Box::pin(s))
    }
}

struct EchoTool {
    si: Value,
    so: Value,
}

#[async_trait]
impl ToolDef for EchoTool {
    fn id(&self) -> &str {
        "echo"
    }
    fn description(&self) -> &str {
        "echo any payload"
    }
    fn input_schema(&self) -> &Value {
        &self.si
    }
    fn output_schema(&self) -> &Value {
        &self.so
    }
    async fn invoke(&self, _ctx: &AgentContext, input: &Value) -> Result<Value, OrkError> {
        Ok(input.clone())
    }
}

struct StubWorkflow;
impl WorkflowDef for StubWorkflow {
    fn id(&self) -> &str {
        "noop"
    }
    fn description(&self) -> &str {
        "noop workflow"
    }
    fn referenced_tool_ids(&self) -> &[String] {
        &[]
    }
    fn referenced_agent_ids(&self) -> &[String] {
        &[]
    }
    fn run<'a>(
        &'a self,
        _ctx: AgentContext,
        input: Value,
        _deps: WorkflowRunDeps,
    ) -> futures::future::BoxFuture<
        'a,
        Result<ork_core::ports::workflow_run::WorkflowRunHandle, OrkError>,
    > {
        Box::pin(async move { Ok(ImmediateWorkflowRunHandle::completed(input)) })
    }
}

fn fixture_app() -> OrkApp {
    OrkApp::builder()
        .environment(Environment::Development)
        .agent(EchoAgent::new("weather"))
        .agent(EchoAgent::new("translator"))
        .workflow(StubWorkflow)
        .tool_dyn(std::sync::Arc::new(EchoTool {
            si: json!({ "type": "object" }),
            so: json!({ "type": "object" }),
        }))
        .server(ServerConfig::default())
        .build()
        .expect("fixture app")
}

#[test]
fn openapi_spec_contains_per_component_paths() {
    let app = fixture_app();
    let spec = ork_api::openapi_spec(&app);

    let paths: Vec<&String> = spec.paths.paths.keys().collect();
    let path_set: std::collections::BTreeSet<&str> = paths.iter().map(|s| s.as_str()).collect();

    assert!(path_set.contains("/api/agents"), "missing /api/agents");
    assert!(
        path_set.contains("/api/agents/weather/generate"),
        "missing per-agent generate route, got {path_set:?}"
    );
    assert!(
        path_set.contains("/api/agents/weather/stream"),
        "missing per-agent stream route"
    );
    assert!(
        path_set.contains("/api/agents/translator/generate"),
        "missing translator generate route"
    );
    assert!(
        path_set.contains("/api/workflows/noop/run"),
        "missing workflow run route"
    );
    assert!(
        path_set.contains("/api/tools/echo/invoke"),
        "missing tool invoke route"
    );
    assert!(path_set.contains("/api/manifest"), "missing /api/manifest");
}

#[test]
fn openapi_spec_components_include_per_dto_schemas() {
    let app = fixture_app();
    let spec = ork_api::openapi_spec(&app);
    let components = spec.components.expect("components present");
    for name in [
        "AgentSummary",
        "AgentDetail",
        "AgentGenerateInput",
        "AgentGenerateOutput",
        "WorkflowRunInput",
        "ToolDetail",
        "ErrorEnvelope",
    ] {
        assert!(
            components.schemas.contains_key(name),
            "missing schema {name}"
        );
    }
}

#[test]
fn openapi_spec_is_deterministic_across_calls() {
    let app = fixture_app();
    let a = serde_json::to_string(&ork_api::openapi_spec(&app)).unwrap();
    let b = serde_json::to_string(&ork_api::openapi_spec(&app)).unwrap();
    assert_eq!(a, b, "openapi_spec(&app) must be deterministic");
}
